/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_16 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] s
  );
  
  
  
  reg [3:0] effeciveB;
  
  always @* begin
    effeciveB = b[0+3-:4];
    
    case (alufn[0+1-:2])
      2'h1: begin
        s = a >> effeciveB;
      end
      2'h3: begin
        s = $signed(a) >>> effeciveB;
      end
      2'h0: begin
        s = a << effeciveB;
      end
      default: begin
        s = a;
      end
    endcase
  end
endmodule
